---
title: "About"
output: html_document
---

Hello again!

Provided below is a summary of my academic and professional background. A full resume can be requested via email from the drop down menu.

## Academic Experience

* Columbia Mailman School of Public Health May 2024
	 + MPH in Epidemiology / Certificate in Chronic Disease Epidemiology
   + Relevant Coursework: Principles and Applications of Epidemiology (I-III), Chronic Disease, Epidemiology, Clinical Epidemiology, Data Science, Emerging Infectious Disease
  
* University of Pittsburgh, April 2019
   + BA in Emergency Medicine / Minor in Chemistry 

## Professional Experience

 * *Paramedic*, City of Pittsburgh EMS, Jan 2019 - August 2022
   + Assess and treat medical and trauma patients in the field and determine if transport to definitive care is necessary
   + Collaborate with other emergency personnel and Medical Command physicians in the treatment and transport decisions of patient cases

 * *Research Assistant*, Columbia University, May 2023 - present
   + Recruit, screen, and monitor subjects for data collection, adhering to IRB protocol, through actigraphy, blood pressure, blood glucose, and blood samples
   + Manage project databases and disseminate results and progress with principal investigator and team members
