---
title: "Austin's Website"
output: html_document
---

## Greetings!

Welcome to my website! 

My name is Austin, I am a MPH graduate from the Columbia Mailman School of Public Health in the Epidemiology department with a certificate in Chronic Disease Epidemiology.

I am currently involved in clinical and health data research by which to further advance health equity and healthcare delivery and further develop my analytical and statistical programming skills. I hope this website, along with my github, provides a small portfolio by which to exemplify my strong foundation in R as well as my problem solving and critical thinking abilities.

This website was created for an assignment under the mentorship of Jeff Goldsmith through his [Data Science I](https://p8105.com/index.html) course.

Feel free to head over to my [about page](about.html) to learn more about my academic and professional background or explore the rest of the site via the menu on the top right.

Here is a [plot.ly flexdashboard](nyc_inspections_flexboard.html) that I also created for the assignment.

Stay as long as you'd like, I'll be here working on other projects.

<iframe src="https://giphy.com/embed/ZDxrPdX4Au7St8r36N" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/MicrosoftCloud-microsoft-cloud-ms-ZDxrPdX4Au7St8r36N"></a></p>

Hope you enjoy the rest of your day!


